baseURL = "https://zakkyaku-dou.pages.dev/"
languageCode = "ja-jp"
title = "雑客堂"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true