[en]
label = "English"
weight = 1
title = "雑客堂"
enableEmoji = true
locale = "en"

[en.params]
description = "Sample article description"
author = "John Doe"
dateFormat = "2006-01-02"
highlightCode = true