showReadingTime = true
mainSections = ["posts"]

disableSpecial1stPost = true

[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 10000
threshold = 0.2
minMatchCharLength = 1
keys = ["title", "summary", "content"]